# Generated by Django 4.0.3 on 2022-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0002_alter_customuser_typeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='typeUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_host',
            field=models.BooleanField(default=False, verbose_name='Are you host?'),
        ),
    ]
