# Generated by Django 4.0.3 on 2022-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0004_remove_customuser_is_host_customuser_typeuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='typeUser',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('host', 'Host')], max_length=100, null=True),
        ),
    ]
