# Generated by Django 4.0.3 on 2022-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0005_alter_customuser_typeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='city',
            field=models.CharField(default='Warszawa', max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
