# Generated by Django 4.0.3 on 2022-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0006_joboffer_city_alter_joboffer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='tel_number',
            field=models.IntegerField(default=0),
        ),
    ]
