# Generated by Django 4.0.3 on 2022-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0007_joboffer_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
