# Generated by Django 4.0.3 on 2022-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0008_alter_joboffer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
