# Generated by Django 4.0.3 on 2022-05-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0009_alter_joboffer_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
