# Generated by Django 4.0.3 on 2022-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0011_alter_joboffer_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='latitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='longitude',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
