# Generated by Django 4.0.3 on 2022-05-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0013_remove_joboffer_latitude_remove_joboffer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='image',
            field=models.ImageField(default=False, upload_to='static/images'),
        ),
    ]
