# Generated by Django 4.0.3 on 2022-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0014_joboffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
