# Generated by Django 4.0.3 on 2022-05-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZO', '0019_alter_joboffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='latitude',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='longitude',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
